### ISSUE TITLE
No longer works?

### ISSUE THREAD

**Issue by roarapps** [cheekyavo/cheekyavo#10]
With property price down, is this also dead?

main-es2015.74098de22de749cc1eeb.js:1 Could not find `Raven`.

**Comment by cheekyavo** [comment]
@roarapps as is, yes, this is currently down.

I am in the middle of my move to NZ, so didn't have time to fix it. I will be working on the the permanent solution and a fix in the next few weeks, once my family is settled in New Zealand. Thank you for understanding.
