### ISSUE TITLE
Fetched page requires javascript

### ISSUE THREAD

**Issue by craigstanton** [cheekyavo/cheekyavo#2]
I've entered a sample URL and it fails because the content it downloads does not contain the text "property type".

https://www.trademe.co.nz/a/property/residential/sale/auckland/north-shore-city/pinehill/listing/3473392311

This can be verified by hitting that address using cURL or simply turning off Javascript in my browser

Running on MacOS 11.6.3, node 12.22.7

**Comment by cheekyavo** [comment]
No longer relevant since it's now an extension. Thank you!
