### ISSUE TITLE
TradeMe search URLs including single quotes returning 404

### ISSUE THREAD

**Issue by ralius18** [cheekyavo/cheekyavo#5]
When checking for the listing price, URLs including single quotes return a 404 error because TradeMe omits them in the base URL (they are fine in the query string)
Other special characters may need to be handled as well

**Comment by ralius18** [comment]
Attempting a fix to retrieve the URLs from the last breadcrumbs
Pull Request created: #6

**Comment by cheekyavo** [comment]
Resolved with https://github.com/cheekyavo/cheekyavo/pull/6
